### ISSUE TITLE
MRPT Compilation error on ARM architecture

### ISSUE THREAD

**Issue by bergercookie** [MRPT/mrpt#324]
Hi @jlblancoc,

I tried compiling MRPT from source on ARM. Compilation failed with the following error message:

[  3%] Building CXX object libs/base/CMakeFiles/mrpt-base.dir/src/poses/CPose2D.cpp.o
/home/linaro/mrpt_upstream/libs/base/src/math/ransac_applications.cpp: In function ‘void mrpt::math::ransac_detect_3D_planes(const Eigen::Matrix<T, -0x00000000000000001, 1>&, const Eigen::Matrix<T, -0x00000000000000001, 1>&, const Eigen::Matrix<T, -0x00000000000000001, 1>&, std::vector<std::pair<unsigned int, mrpt::math::TPlane> >&, double, size_t)’:
/home/linaro/mrpt_upstream/libs/base/src/math/ransac_applications.cpp:163:6: error: no matching function for call to ‘make_pair(std::vector<unsigned int>::size_type&, mrpt::math::TPlane&)’
/home/linaro/mrpt_upstream/libs/base/src/math/ransac_applications.cpp:163:6: note: candidate is:
/usr/include/c++/4.6/bits/stl_pair.h:262:5: note: template<class _T1, class _T2> std::pair<typename std::__decay_and_strip<_T1>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
/home/linaro/mrpt_upstream/libs/base/src/math/ransac_applications.cpp: In function ‘void mrpt::math::ransac_detect_2D_lines(const Eigen::Matrix<T, -0x00000000000000001, 1>&, const Eigen::Matrix<T, -0x00000000000000001, 1>&, std::vector<std::pair<unsigned int, mrpt::math::TLine2D> >&, double, size_t)’:
/home/linaro/mrpt_upstream/libs/base/src/math/ransac_applications.cpp:338:6: error: no matching function for call to ‘make_pair(std::vector<unsigned int>::size_type&, mrpt::math::TLine2D&)’
/home/linaro/mrpt_upstream/libs/base/src/math/ransac_applications.cpp:338:6: note: candidate is:
/usr/include/c++/4.6/bits/stl_pair.h:262:5: note: template<class _T1, class _T2> std::pair<typename std::__decay_and_strip<_T1>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
make[2]: *** [libs/base/CMakeFiles/mrpt-base.dir/src/math/ransac_applications.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

Information about the platform and gcc version as well as the full output of the compilation procedure are also given below:

[sys_info.txt](https://github.com/MRPT/mrpt/files/479987/sys_info.txt)
[20160919_mrpt_compilation_error.txt](https://github.com/MRPT/mrpt/files/479988/20160919_mrpt_compilation_error.txt)

Thanks in advance,

**Update**
Problem seems to be fixed when upgrading g++ to 4.8 version.

**Comment by jlblancoc** [comment]
I would not worry much about this... excepting for the support to Ubuntu 12.04 in PPAs, which also report the same error due to an old GCC version: 
https://launchpadlibrarian.net/282620150/buildlog_ubuntu-precise-amd64.mrpt_1%3A1.5.0~snapshot20160904-1719-git-5bbdccdd-precise-1~ppa1~precise_BUILDING.txt.gz

Thanks for reporting, we'll see how to workaround this...
