### ISSUE TITLE
OSX bayesianTracking

### ISSUE THREAD

**Issue by hucarlos** [MRPT/mrpt#71]
I have the next error when i try to compile te bayesianTracking example

In file included from /Users/aslan/Documents/mrpt-git/samples/bayesianTracking/test.cpp:14:
/usr/local/include/mrpt/bayes/include/mrpt/bayes/CKalmanFilterCapable.h:1438:8: error: invalid use of incomplete type 'detail::CRunOneKalmanIteration_addNewLandmarks'
                                                detail::CRunOneKalmanIteration_addNewLandmarks()(_this, Z, data_association,R);
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/mrpt/bayes/include/mrpt/bayes/CKalmanFilterCapable.h:56:10: note: forward declaration of 'mrpt::bayes::detail::CRunOneKalmanIteration_addNewLandmarks'
                struct CRunOneKalmanIteration_addNewLandmarks;
                       ^
In file included from /Users/aslan/Documents/mrpt-git/samples/bayesianTracking/test.cpp:22:
/usr/local/include/mrpt/base/include/mrpt/math/distributions.h:204:6: error: no viable overloaded '_='
                        Hc_=1.0/ mrpt::math::maximum(Hc);
                        ~~^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *_\* [CMakeFiles/bayesianTracking.dir/test.o] Error 1
make[1]: **\* [CMakeFiles/bayesianTracking.dir/all] Error 2
make: **\* [all] Error 2

I am working on Maveriks 10.9.4
